- pym/bob/cmds/jenkins.py
- convert windows to msys paths
- use bash
> fix #11: jenkins: produce windows (msys2) compatible scripts

- doc/manual/manual/configuration.rst
- pym/bob/input.py
- test/test_input_stringparser.py
Add `or` and `and` to string substitution functions.
> Add boolean funcs

- doc/manual/manual/configuration.rst
- pym/bob/input.py
- test/test_input_stringparser.py
The first commit adds a function called 'match' for regex based conditions.
The second commit fixes a typo in the docs.
> Adding function match for regex based conditions.

- doc/manual/manual/configuration.rst
- pym/bob/cmds/build.py
Add documentation and debug facility.
> Sandbox preconditions

- contrib/bash-completion
- doc/manual/tutorial/compile.rst
- pym/bob/cmds/build.py
- pym/bob/input.py
- pym/bob/scripts.py
As discussed on the mailing list this is my first attempt for bob status. 
One question that needs to be discussed is: What should --force-checkout do for url scms or if error is returned from Svn/Git? (Nothing / move to attic / delete old sources without moving to attic )? As a user I would assume that after --force-checkout the sources are in a clean state so moving to attic would the best?
> bob status and --clean-checkout

- doc/manual/manual/extending.rst
> manual: document developNamePersister hook

- test/test_input_gitscm_status.py
As promised this is the test for GitSCM.status.
> test: add git status test

- pym/bob/input.py
- test/test_input_gitscm_status.py
- test/test_input_svnscm_status.py
This fixes SVN status for empty directories. Also added documentation and a status test for svn.
> Svn status

- doc/manual/manual/configuration.rst
- pym/bob/cmds/misc.py
- pym/bob/input.py
A different approach for the 'alias' feature. Just to be sure this is the way to go before going further...
What do you think about using the alias in bob's output? for example if there is a alias `my_lib: root/lib` you can now call `bob dev my_lib` but the output is
```
$ bob dev my_lib
>> root/lib
```
IMO this shouldn't be changed. It's more reasonable what's build with this alias.
> Alias [RFC]

- doc/manual/configuration.rst
- pym/bob/archive.py
- pym/bob/cmds/build.py
- pym/bob/cmds/jenkins.py
- pym/bob/input.py
Refactors the binary artifact handling and provides a "shell" backend that might use any command for the actual up- or download.
> Shell command archive

- contrib/bash-completion
- doc/manpages/bob-ls.rst
- doc/manpages/bob-project.rst
- doc/manpages/bob-query-recipe.rst
- doc/manpages/bob-query-scm.rst
- doc/manpages/bob-status.rst
- doc/tutorial/compile.rst
- doc/tutorial/getting_started.rst
some minor updates for the man pages.
bash completion available for bob help. also added --destination option for bob dev/build.
> Doc & bash completion updates

- doc/manpages/bob-jenkins.rst
- pym/bob/cmds/jenkins.py
- test/jenkins/jenkins_mock.py
- test/test_jenkins.py
- test/test_jenkins_set_options.py
This PR is only to check if the jenkins mock is basically working on travis... :wink:
> started jenkins unit testing..

- pym/bob/__init__.py
- pym/bob/input.py
- pym/bob/utils.py
> get rid of CACHE_VERSION ... 

- pym/bob/input.py
Typically not all tools are used in the package of the referenced step.
They can be left out in the diff calculation which speeds it up
considerably.
> input: only store relevant tools in CoreStepRef

- Makefile
- bob-audit-engine
- doc/manual/audit-trail.rst
- doc/manual/concepts.rst
- doc/manual/index.rst
- doc/tutorial/compile.rst
- pym/bob/archive.py
- pym/bob/audit.py
- pym/bob/cmds/build.py
- pym/bob/cmds/jenkins.py
- pym/bob/input.py
- pym/bob/scm/__init__.py
- pym/bob/scm/cvs.py
- pym/bob/scm/git.py
- pym/bob/scm/scm.py
- pym/bob/scm/svn.py
- pym/bob/scm/url.py
- pym/bob/scripts.py
- test/stable-variant-ids/specs/checkouts.txt
- test/stable-variant-ids/specs/env.txt
- test/stable-variant-ids/specs/include.txt
- test/stable-variant-ids/specs/sandbox.txt
- test/stable-variant-ids/specs/tools.txt
The audit trail feature is meant to track everything that was used to create a certain artifact. This includes the state of the SCMs, the host(s) that any part was built on and more. The tracking shall be seamless across local and Jenkins builds and include binary artifacts.
> WIP: Audit trail

- pym/bob/input.py
Provide the properties to the virtual root package.
fixes #148
> input: fix properties on virtual root

- pym/bob/cmds/jenkins.py
At the moment archived artifacts are deleted if the associated recipe isn't a root recipe. If you use 'jenkins add-root' this 'root' will be discarded.
- does not matter if jenkins root is root recipe
> jenkins: 'discard builds' deactivated for 'roots'

- pym/bob/scm/cvs.py
'cvs co' does not have a '-P' option like 'cvs up' has.  That option removes
empty (=deleted) directories.  We therefore use a 'cvs up' after the initial
'cvs co', to get the same behaviour for the initial and subsequent builds.
Previously, 'cvs co' would have created these empty directories, causing bob
to invoke the build step even if nothing changed in the repository between
initial and subsequent checkout.
> cvs: prune empty directories on initial checkout

- pym/bob/input.py
I noticed that you add all results into a list and filter it afterwards. Why not checking this before adding them? It would be a little performance improvement - I noticed that it will be done later, too, with provideDeps, but at first I wanted to hear your opinion.
> WIP: input: filter duplicate steps while calculation - not afterwards

- pym/bob/cmds/graph.py
Added a checkbox to the html page which hightlights the packages
depending on the selected package. Also shrinked the svg to make
the whole content fit into the window.
> graph(d3): hightligh packages depending on the selected

- pym/bob/input.py
- pym/bob/stringparser.py
Add some optimizations that improve the parsing speed.
Fixes #177.
> Improve package parsing speed

- doc/manual/configuration.rst
- pym/bob/input.py
- test/checkoutAssert/recipes/root.yaml
- test/checkoutAssert/recipes/root_fail.yaml
- test/checkoutAssert/recipes/src/gpl3.txt
- test/checkoutAssert/run.sh
- test/test_input_step.py
+ checkoutAssert as discussed in #194
> Checkout assert

- pym/bob/cmds/build.py
Make sure that develop directories are unique when taking over previously calculated values on recipe changes.
Fixes #201
> Fix crash when updating recipes

- pym/bob/cmds/build.py
- pym/bob/cmds/graph.py
- pym/bob/cmds/jenkins.py
- pym/bob/cmds/misc.py
- pym/bob/utils.py
Defines containing "=" caused Bob to exit with an error, which is not intended.
Furthermore simplified `processDefines` function as suggested by @jkloetzke and used it consistently over the whole code base.
Fixes #200
> Fix processing of defines

- pym/bob/audit.py
In dev mode a common used scenario is to rebuild after a small code
change. For this generating the audit trail may take a significant amount of
time or even more time compared to the real compile time.
For a large module with some dependencies a
```bob dev -b <module>```
takes 1:15min with audit trail and 0:30min without after modifying a
single line of code.
This change disable the audit trail for 'bob dev' unless upload is
enabled and adds some controll switches.
> build: do not generate audit trail in dev mode

- pym/bob/cmds/graph.py
People reported bob graph needs ~1.5h. Fix it by stopping recursive
calls if the package is already processed.
> graph: stop recursion earlier

- .travis.yml
- Makefile
- bob
- doc/manpages/bob-build-dev.rst
- doc/manpages/bob-build.rst
- doc/manpages/bob-dev.rst
- doc/manpages/bob-project.rst
- doc/tutorial/getting_started.rst
- pym/bob/__init__.py
- pym/bob/archive.py
- pym/bob/audit.py
- pym/bob/cmds/build.py
- pym/bob/errors.py
- pym/bob/input.py
- pym/bob/scm/git.py
- pym/bob/scm/scm.py
- pym/bob/scm/url.py
- pym/bob/scripts.py
- pym/bob/tty.py
- test/jenkins/jenkins_mock.py
- test/parallel/recipes/lib1.yaml
- test/parallel/recipes/lib2.yaml
- test/parallel/recipes/lib3.yaml
- test/parallel/recipes/root.yaml
- test/parallel/run.sh
- test/status/default.yaml
- test/test-lib.sh
- test/test_archive.py
- test/test_input_gitscm.py
- test/test_input_urlscm.py
Add the '-j' option to build packages in parallel.
> Parallel builds

- contrib/bash-completion
- doc/manpages/bob-query-meta.rst
- doc/manpages/bob-query-recipe.rst
- doc/manpages/bob-query-scm.rst
- doc/manpages/bob-status.rst
- pym/bob/cmds/build/status.py
- pym/bob/cmds/misc.py
Add --sandbox / --no-sandbox as it was missing before.
Fixes #192
> status/query: add sandbox argument

- pym/bob/scm/url.py
This fallback has some limitations:
- wget doesn't support as much protocols as curl, but for the usual
HTTP(S) and FTP it does the job
- the time-stamp mechanism (-N) can't be used as with curl, because wget
doesn't support it together with own outputfile names (-O)
The motivation of this change was to lower the dependencies for simple
tasks.
Maybe there is a simple solution for the time-stamp approach.
> url: Use wget as fallback in case curl isn't available

- pym/bob/generators/VisualStudio.py
- pym/bob/generators/__init__.py
- pym/bob/generators/common.py
- test/generator/plugins/generator.py
- test/generator/run.sh
The first implementation that works on MSYS2. Full support for VS would require that Bob runs natively on Windows which is not possible (yet).
Fixes #248.
> Visual Studio 2019 generator

- pym/bob/input.py
> input: fix crash on incompatible provided variants

- pym/bob/cmds/build/builder.py
As reported on #266 Bob will deadlock when using recursive sandboxes...
> Fix deadlock on recursive sandboxes

- pym/bob/cmds/build/builder.py
If a job fails the overall execution is stopped and no more tasks are
started. Since buildId calculation is also a executed as a task the
buildId of a parallel running successfull job was not calculated and the
build was executed in the next bob build.
Handle this by adding a ignoreExecutionStop argument to __yieldJobWhile.
This argument should be set to true for all 'cleanup' tasks.
Fixes #271.
> builder: do not cancel buildId calculation

- .travis.yml
- test/jenkins/jenkins_mock.py
- test/run-tests.sh
- test/test-lib.sh
- test/test_jenkins.py
- test/test_jenkins_set_options.py
Let's run the tests in parallel if possible. Also test on Python 3.7 and 3.8 for the sake of completeness.
> Improve testing speed and coverage

- pym/bob/cmds/build/query.py
In case that no paths for the given query could be found, present a
message to the user stating exactly that. Bob's silence in these cases
could be quite confusing.
Note that since query-path is mainly used for scripting purposes and
these scripts may rely on the empty output, the message is printed to
stderr.
Update the copyright statement whilst we're at it.
> query-path: Show message on empty output

- doc/manual/configuration.rst
- pym/bob/input.py
- pym/bob/scm/scm.py
- test/status/default.yaml
- test/status/run.sh
Add 'if' keyword to scmOverrides to selectively enable or disable
scmOverrides.
> input: add support for 'if' in scmOverrides

- pym/bob/archive.py
- pym/bob/cmds/build/builder.py
- pym/bob/cmds/jenkins.py
- pym/bob/input.py
- pym/bob/scripts.py
- pym/bob/utils.py
- test/test_utils.py
Make sure we don't accidentially share artifacts between the different platforms.
> Platform differentiation

- .travis.yml
- pym/bob/cmds/build/builder.py
- pym/bob/invoker.py
- pym/bob/languages.py
- test/pwsh/config.yaml
- test/pwsh/recipes/file.txt
- test/pwsh/recipes/root.yaml
- test/pwsh/recipes/sandbox.yaml
- test/pwsh/run.sh
An while we are at it add a PowerShell test case...
> Keep generated scripts next to workspace

- pym/bob/audit.py
- pym/bob/cmds/build/builder.py
- pym/bob/cmds/graph.py
- pym/bob/cmds/jenkins.py
- pym/bob/generators/QtCreatorGenerator.py
- pym/bob/input.py
- pym/bob/invoker.py
- pym/bob/scm/__init__.py
- pym/bob/scm/git.py
- pym/bob/scm/imp.py
- pym/bob/scm/scm.py
- pym/bob/scm/svn.py
- pym/bob/scm/url.py
- pym/bob/scripts.py
- pym/bob/utils.py
- test/test_scm_import.py
- test/test_utils.py
Improve the integration and speed of git audits.
Improves #318.
> Improve git audit

- pym/bob/invoker.py
Before Bob 0.17 all commands, including checkout asserts and SCMs, were
compiled into one big bash script and executed in the same environment.
Starting with the multi language support the SCMs are directly invoked
by Bob. This lead to a regression where these commands would not get the
checkoutVars added to their environment any more.
Change the invoker to always apply the step environment. This is only
disabled for the fingerprint scripts (that have their own
'fingerprintVars' setting) and the checkout/build/packageScript itself
because the language handler already takes care of it.
Fixes #355.
> invoker: run commands with step environment by default

- doc/manual/configuration.rst
- pym/bob/scm/git.py
- test/test_input_gitscm.py
- test/test_input_gitscm_status.py
First shot for supporting submodules. This is way more heavy than I anticipated. @rhubert please have a look if there is something obvious missing. In principle only the `submodules` and `recurseSubmodules` properties need to be set and you're good. :crossed_fingers:
> Submodules

- doc/manual/configuration.rst
- pym/bob/cmds/jenkins.py
- pym/bob/input.py
- pym/bob/languages.py
- test/setup-scripts/classes/inert.yaml
- test/setup-scripts/config.yaml
- test/setup-scripts/recipes/root.yaml
- test/setup-scripts/run.sh
@stefanreuther Good things come to those who wait. :wink: I finally found the time to implement the requested feature. Please have a look. I think this PR should fully address #37.
> Setup scripts

- pym/bob/cmds/jenkins.py
- pym/bob/input.py
@mahaase Can you test if this fix for #384 fully solves the issue for you?
> Fix missing checkouts on Jenkins

- doc/installation.rst
how to install `bob` on a machine without internet access??
I haven't found a easy solution to do this but it's working with the steps described in the PR. :man_shrugging:
> [RFC] doc: some notes about offline installations

- pym/bob/generators/VisualStudio.py
> generators/VisualStudio: add additional includes by -I argument

- contrib/bash-completion/bob
- doc/manpages/bob-build-dev.rst
- doc/manpages/bob-build.rst
- doc/manpages/bob-clean.rst
- doc/manpages/bob-dev.rst
- doc/manual/configuration.rst
- pym/bob/cmds/build/build.py
- pym/bob/cmds/build/builder.py
- pym/bob/cmds/build/clean.py
- pym/bob/cmds/build/share.py
- pym/bob/cmds/jenkins.py
- pym/bob/input.py
- pym/bob/languages.py
- pym/bob/state.py
- pym/bob/utils.py
- test/shared-cleanup/config.yaml
- test/shared-cleanup/recipes/root.yaml
- test/shared-cleanup/run.sh
- test/shared-pkg/config.yaml
- test/shared-pkg/recipes/root.yaml
- test/shared-pkg/run.sh
- test/test_utils.py
This has been tested moderately. Even though it *should* work on Windows I did not test it there yet. A couple of test are also missing.
@mahaase @danielroedl This might be interesting for you I guess. Any testing and feedback is welcome.
> Local shared packages

- .travis.yml
- pym/bob/utils.py
- test/cyclic-classes/run.sh
- test/run-tests.sh
> Improve coverage

- pym/bob/invoker.py
On Windows environment variables are case-insensitive but
case-preserving. Unfortunately MSYS2 creates variables that only differ
in case (e.g. TMP vs. tmp). Remove the hard failure from the check and
convert it into a warning because Bob versions before 0.17 worked
without failure in this case. Also fix the code to catch all possible
collisions, including ones that are created by the recipes itself.
Fixes #432.
> invoker: do not fail on environment variable collisions

- doc/manual/configuration.rst
- pym/bob/input.py
- pym/bob/scm/cvs.py
- pym/bob/scm/git.py
- pym/bob/scm/imp.py
- pym/bob/scm/svn.py
- pym/bob/scm/url.py
- test/test_input_recipeset.py
Fixes: #429
Not sure if this fits. The higher layer would override the setting of a lower layer... :/
> git: add defaultBranchName

- doc/manual/configuration.rst
- pym/bob/scm/git.py
- test/git-alternatives/default.yaml
- test/git-alternatives/recipe1.yaml
- test/git-alternatives/recipe2.yaml
- test/git-alternatives/run.sh
> Git references

- pym/bob/cmds/jenkins.py
Since version 1.44, the Copy Artifact plugin checks permissions more
thoroughly in its default "Production mode". If the anonymous user has
no right to read jobs and its artifacts, the copy will fail. In such a
configuration Bob required to use "Migration mode" which opens some
security loopholes.
Because we known which jobs require access to the artifacts, Bob will
now whitelist these jobs explicitly. This works regardless of the user
configuration.
> jenkins: improve copyartifact compatibility

- pym/bob/scm/git.py
If a commit is only on a tag but not on a branch the tag was shown as unpushed.
> git: fix status output for commits only on tags

- pym/bob/scm/git.py
If a repo was moved to a new commit and the commitID was updated in the recipe to the same commit, the previous behavior was to switch to the new commit running the checkout again including all checks.
In pratice there are cases where the new commit hasn't been pushed to the configured branch when running bob again. The commitOnBranch check noticed that the commit did not match the branch and the build fails. To recover from this a developer needs to either move it's stuff back from the attic, write a scmOverride, ... which is annoying and not really necessary as the workspace is already on the correct commit.
To make this more user friendly relax the "Branch ... did not contain .." error if the workspace is on the configured commit and leave the workspace untouched.
> git: relax the gitCommitOnBranch check

- pym/bob/builder.py
> fix typo for checkoutReason

- doc/manpages/bob-build-dev.rst
- doc/manual/configuration.rst
- pym/bob/cmds/layers.py
- pym/bob/layers.py
Some minor things that popped up while testing the layers SCM features....
> Polish layers

- .github/workflows/workflow.yaml
Jenkins requires Java 17 or 21 these days.
> workflow: update java version

- doc/manpages/bob-query-recipe.rst
- pym/bob/cmds/misc.py
> Extend query recipe

- contrib/bash-completion/bob
- doc/conf.py
- doc/manpages/bob-ls-recipes.rst
- doc/manpages/index.rst
- pym/bob/cmds/misc.py
- pym/bob/input.py
- pym/bob/scripts.py
- test/black-box/commands/run.sh
- test/black-box/ls-recipes/config.yaml
- test/black-box/ls-recipes/recipes/lib.yaml
- test/black-box/ls-recipes/recipes/root.yaml
- test/black-box/ls-recipes/recipes/unused.yaml
- test/black-box/ls-recipes/run.sh
> Add new 'ls-recipes' command

- .github/workflows/workflow.yaml
- pym/bob/input.py
- test/run-tests.sh
Give the user more hints if a deeper layer requires a higher Bob version than the project/layer(s) above.
> input: improve error message of layer version conflicts
