BobBuildTool/bob

pym/bob/state.py
After fixing my msys / mingw installation (do not use mingw python, use msys python) the only remaining issue is the failing rename if the target file exists. 
Python-docu:
> On Windows, if dst already exists, OSError will be raised even if it is a file.
=> fix #5: remove pickle file if exits before renaming tmpFile

pym/bob/input.py
os.glob is only woking recursivly for python 3.5 or higher. use os.walk instead, which is available for all python3 versions
=> fix #7: input: fix recusive scan for recipies on python < 3.5

pym/bob/cmds/jenkins.py, pym/bob/input.py
This adds https support for jenkins connections. For now the ssl Context is working without certificate check.
It's also possible to set JENKINS_GIT_CREDENTIALS_ID environment variable to the crendentialsID from Jenkins, which is needed for checkout from gitlab.
=> fix #9: input/Jenkins: add security features

doc/manual/manual/configuration.rst, pym/bob/input.py
The eighties called and want their SCM back. Use:
```
checkoutSCM:
scm: cvs
cvsroot: ...
module: ...
dir: ...
rev: tag-or-branch
```
=> add (probably incomplete) CVS support

pym/debug.py
With this it's possible to debug bob in a IDE like the PhyDev Eclipse plugin.
It needs to be in a separate package to get rid of the relative path imports.
Phydev debug configuration setup:
- Main Module: debug.py
- Workspace:   recipe repo, e.g. sandbox
- Arguments:   bob args, e.g. dev vexpress
=> debug bob: added debug main script

test/run-tests.sh
When no `coverage3` is present in the PATH, then `which` says so on
_stderr_:
```
which: no coverage3 in (...$PATH...)
```
=> Fix unexpected output from test/run_tests.sh

test/run-tests.sh
If running the tests inside a venv but coverage is only installed
outside, it was used and thus cannot import packages that are only
installed inside the venv.
This patch tests, if coverage is installed inside the current (v)env and
only uses this and not the outside one.
fix #36
=> test: run coverage only from the current (v)env

test/test_utils_dirhasher.py
Without this change the test output is disturbed by a confusing log
message. Since we expect it, we test for it and suppress it in doing so.
=> test: suppress confusing logmessage

doc/manual/manual/extending.rst
Some revisions of bob 0.4 didn't support project generators -> use apiVersion 0.5 for
projectGenerators. Also fixed the keyword.
=> doc: fix projectGenerator section

pym/bob/cmds/build.py
Bob project runs 'bob dev'. Since this step can fail it should be possible to
use the --resume argument for bob project also.
Fixes #44
=> bob project: add --resume switch

pym/bob/input.py
If bob is executed in a directory without recipes it should leave this
directory without any leftovers.
Fixes #46
=> input: remove shelve file

pym/bob/cmds/build.py, pym/bob/generators/EclipseCdtGenerator.py, test/run-tests.sh
This adds Eclipse CDT support to Bob. All dependencies are added as virtual folders
pointing to the src-directory of the package. For all x86 executables launch configs
will be generated.
What do you think? Shall this also be a build-in generator?
=> bob project: add eclipseProjectGenerator

pym/bob/cmds/build.py, pym/bob/cmds/misc.py, pym/bob/scripts.py, pym/bob/state.py, test/query-path/.gitignore, test/query-path/recipes/child.yaml, test/query-path/recipes/interm1.yaml, test/query-path/recipes/interm2.yaml, test/query-path/recipes/root.yaml, test/query-path/run.sh, test/run-tests.sh
Two new commands.
(a) `query-scm`: solves the problem that your SCM hook tells you "url xyz changed", and you want to know what to rebuild.
(b) `query-path`: allows you to find out where bob put the build result so you can postprocess that automatically (like: upload generated reports to a webserver). Disclaimer: I'm not sure I understood everything that makes up this command :-)
=> [RFD] query-path and query-scm commands

pym/bob/generators/EclipseCdtGenerator.py
Fixed a bug in genereated .cproject when regex matches multiple packages or
--exclude is used more than once.
=> eclipseGenerator: fix multiple exclude packages

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py, pym/bob/utils.py
There are two "magic" modules with similar functionality. Find out which one
we got and adapt.
Discussion: http://stackoverflow.com/questions/25286176/how-to-use-python-magic-5-19-1
Debian has the "wrong one" as python3-magic, causing the blackbox tests to bomb out with
>     Run test/generator
>     An internal Exception has occured. This should not have happenend.
>     Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
>     Traceback (most recent call last):
>       File "/home/stefan/extsrc/bob/pym/bob/scripts.py", line 103, in bob
>         availableCommands[verb][1](argv, bobRoot)
>       File "/home/stefan/extsrc/bob/pym/bob/scripts.py", line 47, in __project
>         doProject(*args, **kwargs)
>       File …
=> project: adapt to different magic modules

contrib/bash-completion
zsh doesn't have (and need) _get_comp_words_by_ref __ltrim_colon_completions.
fixes #52
=> completion: differ between zsh and bash

contrib/bash-completion
This adds completion for query-path, query-scm and query-recipe.
On bash it's not working if you use a unquoted or unescaped format sting.
@stefanreuther I think the brace expansion in bash breaks completion. Can we use another character for the braces in the format strings?
=> bash-completion: query-path query-scm query-recipe

contrib/bash-completion
bob project --list needs to generatePackages wich takes a long time on large projects
and issn't needed for completion of packages.
=> bash-completion: speedup bob project completion

doc/manual/tutorial/compile.rst, pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
With this you can add additional included directories (-I) to eclipse and
QtCreator projects. This may be usefull if some compiling for host where /usr/include
is unkown for bob.
For QtCreator you can now also add aditional files (e.g. *.ui) to project using a regex (-f <regex>).
=> Project additional includes

pym/bob/cmds/build.py, pym/bob/input.py
In case of a aborted checkout git may be in a unclean state. For this reason some
git commands are returning a error. GitSCM.status has been modified to print the
error without raising a exception.
=> input: handle git errors smoothly

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
With --clean the generator removes the destination directory before generating
the project files. This may be usefull in case of a non working project because of
changes in the creator.user file.
The --buildCfg argument can be used to add additional buildConfigs. For example
--buildCfg "Bob dev DEBUG"::"-b -DDEBUG=1".
=> Qt/EclipseGenerators: clean and buildCfg argument

pym/bob/__init__.py
The fallback output of git describe is not parseable by utils.compareVersion.
Removed this argument.
=> bob: fix getVersion

doc/manpages/bob-project.rst, pym/bob/generators/QtCreatorGenerator.py
Added the option to exclude projects for the qtcreator project.
This is a bit different than for eclipse:
No sym link and no include files will be created. Else qtcreator will parse all the files which we want to avoid. 
~Mark
=> Added exclude option to qtcreator project file generation

doc/manpages/bob-project.rst, pym/bob/cmds/build.py
Added the option for a build only mode when creating projects:
bob project -b
does the same as bob dev -b (no checkout).
This should solve the issue that -n has but will allow you to generate a project if -n fails but you don't want to do a checkout.
~Mark
=> Added build only (no checkout) as option for bob project

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
Added a Debug and Clean build target. 
I think it would be easier just to choose a different build target if you need a debug buil than to create a new project file. 
How do you even develop without a proper debug build? I think this should always be an option as a build target for developing.
~Mark
=> Added some more build targets

pym/bob/cmds/build.py, pym/bob/scm/cvs.py
Simple, brute-force implementation using `cvs update` as the basis. It will therefore contact the server and tell you where the server's branch differs from yours (instead of just your local modifications), but everything else probably involves manually parsing CVS's metadata files.
I'm not sure how this interacts with the `status()` call in `_cookCheckoutStep`. Documentation about the expected behaviour would have helped :-)
=> cvs scm: implement 'bob status'

pym/bob/cmds/misc.py, test/commands/.gitignore, test/commands/recipes/root.yaml, test/commands/run.sh, test/commands/testconfig.yaml
Make ls, query-recipe and query-scm able to use -D and -c arguments. Also added a small unit test testing all highlevel commands if they are aware of -D and -c argument.
=> misc-cmds: make use of defines and config file.

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
Accept a OSError while searching for executables. e.g. 'FileNotFoundException'
in case of a broken symlink.
=> Qt/EclipseGenerator: fix crash on broken symlink

Makefile
The new version will no longer write something like `[SHORT_COMMIT_HASH]-dirty` into the version file. That caused bob's version check to fail.
=> Fixes versioning via Git.

doc/manpages/bob-project.rst, pym/bob/generators/QtCreatorGenerator.py
Added the QtCreator `--use-only` feature as discussed in PR #80 .
Tested and it worked to include only projects.
~ Mark
=> Qtcreator useonly

pym/bob/cmds/build.py, test/rerun-failed-build/recipes/foo.c, test/rerun-failed-build/recipes/root.yaml, test/rerun-failed-build/run.sh
Bob did not internally prepare for the failed execution of a step. Instead the previously determined input and result of the step was kept and no information was left that the work space is in an undefined state.
This PR fixes the problem and adds a test case that previously failed exactly due to the reason above.
Fixes #102
=> Fix handling of interrupted/failed steps

doc/manual/concepts.rst, pym/bob/cmds/build.py, pym/bob/cmds/jenkins.py, pym/bob/input.py
Do not treat tags/commits any different from branches when computing the build-id.
Fixes #106
=> Redefine build-id

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
Do not add a source workspace if it was allready added. This can happen in a
multipacke environment with provided dependencies.
=> QT/Eclipse generators: avoid adding same sources multiple times

pym/bob/scm/git.py
When using git with a version below 1.8.2.1 there is a error after fetching. E.g. this happens when you use CentOS or RedHat.
=> git: change fetch command for git compatibility <1.8.2

pym/bob/scm/scm.py, test/status/default.yaml
Fixes a regression brought in with 914f5f and added replace keyword to unittest.
(fixes #119)
=> scm: fix crash while hashing scmOverrides

pym/bob/cmds/build.py, pym/bob/scm/git.py, pym/bob/scm/svn.py
01b9fc8 changed the return value of scms status from unclean to dirty but missed to adapt the check in clean-checkout.
=> build: fix clean-checkout

doc/manual/configuration.rst
When the build script is called a configure script is not available in the current directory it's only in the source dir.
=> Use srcdir for configure call

doc/manpages/bob-jenkins.rst, pym/bob/cmds/jenkins.py, test/test_jenkins_set_options.py
As discussed in a meeting last week I implemented a parameter to make "jenkins push" and "jenkins export" faster. By inserting a return condition for already visited packages, calculating Jobs just takes some seconds.
=> faster Jenkins job calculation by shorten description

.gitignore, pym/bob/cmds/help.py, pym/bob/scripts.py
I attempted several times to use `bob help` as I'm used from Git & Co. So why not accepting this command verb without any further options as the other cool cats around do?
Yes, this predates the responsibility of the help command implemented in help.py. As this one only handles the help verb with an additional command there should be no trap for young players. A unified/hierarchical argument parser might streamline this.
=> Allow `bob help` as an alternative to `bob --help`

contrib/bash-completion, doc/manpages/bob-jenkins.rst, pym/bob/cmds/jenkins.py
Added a option to make use of the binary artifacts server for sharing
artifacts between jobs. This may lower the load on jenkins master.
=> jenkins: use binary artifact server for sharing

doc/manpages/bob-jenkins.rst, pym/bob/cmds/jenkins.py
Introduce the 'jobs.isolate' extended option. This regular expression isolates any mathing packages into dedicated jenkins jobs.
=> Jenkins isolate packages

Makefile
In order to be able to install different types (numbers) of man pages
this includes a new for loop iterating over all currently present man
page types (numbers). This is extensible more easily than having to
`mkdir` and `cp` for each and every new number.
=> Makes the man page installation more general.

pym/bob/cmds/build.py
Even in case of a downloaded package-result the force option should trigger
a rebuild.
Fixes #147
=> build: fix force option

doc/tutorial/compile.rst
The path to the _static dir is different between 'dirhtml' and 'html'
doc build. Using the correct path for 'html' build which is the same as
readthedocs.
=> doc: fix path to sandbox graph for htmldoc

doc/manual/configuration.rst, pym/bob/scm/git.py, test/test_input_gitscm.py
**Problem this is trying to solve:**
Each time a new source directory is created, because of new tags or branches, or because of creating a new "workspace", i.e. cloning the recipe repository to a new location, the user has to re-add his personal remote repositories.
**Solution:**
Add a `scmOverride` with the users remotes that will be added each time the corresponding repositories are checked out. This would look something like:
```yaml
scmOverride:
match:
url: "git@central/repo/url.git"
remotes:
my_remote: "git@my/remote/url.git"
second_developer: "git@second/developers/url.git"
```
The key will be used as the remote name and the value as the remote URL.
This is a quick implementation to see if it works as expected. And it seems that it does.
So is this something you would consider to …
=> Add git remotes

doc/manual/configuration.rst, doc/manual/policies.rst, doc/tutorial/compile.rst, pym/bob/input.py
The word "recipes" was used interchangeably for the project root
directory (with config.yaml, default.yaml, recipes and classes
directory) and the "recipes" directory inside that itself. Solve this
ambiguity by using a consistent naming of the "project root directory"
which, among other things, contains the "recipes directory".
Fixes #163.
=> doc: fix wording of "recipes" directory

pym/bob/generators/QtCreatorGenerator.py
bob project qt-creator appends two spaces after the contents of the PATH
variable in QtCreator project file. This breaks the last component of the
PATH variable. E.g. it turns "foo:bar:baz" into "foo:bar:baz  " and
whatever would be found in "baz" will not be found when the PATH contains
"baz  " instead.
Remove the extra spaces.
=> bob: don't add spaces after last PATH element

doc/manpages/bob-build-dev.rst, pym/bob/cmds/build.py
With this mode it will be tried to download the desired package artifact at first. If this fails all dependency artifacts must be available
=> build: add forced-fallback download mode

pym/bob/archive.py, pym/bob/cmds/build.py, pym/bob/utils.py
When run under MSYS or Cygwin the OS will be advertised as POSIX. This
is not fully correct because sym- or hard-links are not really working.
Detect these as Windows platform too and fall back to more generic
behaviour.
Fixes #179.
=> bob: handle Windows more thoroughly

bob, bob-audit-engine, bob-hash-engine, bob-hash-tree
With this change it's now possible to use debug and other wrapping applications like the profiler:
```
python3 -m cProfile -o bob-ls.stats $BOB_PATH/bob ls
gprof2dot -f pstats bob-ls.stats | dot -Tpng -o bob-ls.png
```
Since we don't use the other start scripts, I have only testet `bob`.
While we are at it? Why are the other scripts not part of the normal bob runtime and implemented as subcommands?
=> Convert shell startscripts to python

contrib/bash-completion
The bash completion should now pick up any "-C", "-c" and "-D" options
correctly. This will prevent any re-parsing after invoking a bash
completion. This should improve #177 by reducing the number of
re-parsings.
File names with white spaces are still not completed correctly, though.
This needs an additional round of fixing.
=> bash-completion: fix parameter passing

pym/bob/cmds/jenkins.py
Sort the meta environment variables to get a stable job description.
This will avoid setting a new configuration for a unchanged input which
sometimes takes a very long time.
=> jenkins: make a stable job configuration

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
While collecting checkoutdirs we can stop recursion on already known
packages.
(reduces bob project time from 3.5h to 7sec...)
=> generators: skip already known packages

pym/bob/cmds/build.py
Fix KeyError occurring on a bob dev/build --resume without having a valid
.bob-state / bob was not run before.
=> build: fix KeyError in loadBuildState

pym/bob/cmds/build.py
As for bob project stop the recursive search for checkoutSteps when
seeing a processed step again.
=> build: speedup status by stopping recursion

pym/bob/scm/url.py
Add two flags to `tar` invocation that will provide consistent behavior
whether `bob` is executed as root or a normal user.
=> url: tar: use consistent permissions

doc/manual/configuration.rst, doc/releases/0.14.rst, pym/bob/input.py, pym/bob/scm/scm.py, test/test_input_scmoverride.py
Override scms having a common used set of overrides controlled by variables.
This reduces the number of overrides needed when you entered branching hell for your project... :see_no_evil: :hear_no_evil:
I'm not sure if it's a good idea to do the substitution only with the environment from `default.yaml` / command line but I have the feeling that substitution when constructing the `CheckoutStep` using the `fullEnv` is too late. It gives the recipes the possibility to change to override again which might be a pitfall.  :confused:
=> scmOverrides: allow use of variables

doc/releases/0.14.rst, pym/bob/input.py
With 38bc5df1 the behavior of the indirectPackages filter has been
changed. This restores the old behavior avoiding duplicate/missing
dependencies.
I added a small repocase for the 'missing' dependencies. Maybe it was
not correct before 38bc5df1 and this is not a bug? (Although it looks
strange to have a dependency twice in the audit trail..)
[test.tar.gz](https://github.com/BobBuildTool/bob/files/2167846/test.tar.gz)
The main difference is, that in 
```
"package" : "a-foo",
"step" : "build",
```
the dependency for `b` is missing:
Bob 0.14:
``` 
"dependencies" : {
"args" : [
"4cf372d74153954ce130c0f5407baf00841a18dd", a-bar dist
"8715f688fe40af6bc2d1bdd8651afac46c366cd9"  c dist
]
},
```
Bob 0.13:
```  
"dependencies" : {
"args" : [
"9025a0841f1100f142dd1e3a62de9c35d7ac259e", a-bar dist …
```
=> input: fix missing / duplicated indirectPackages

pym/bob/cmds/misc.py
As we did before for bob project and bob status we can  stop the recursive
search when seeing a processed package again.
=> misc: query-scm: stop recursion for known packages

doc/manual/configuration.rst, doc/manual/extending.rst, pym/bob/__init__.py, pym/bob/input.py, pym/bob/stringparser.py, pym/bob/tty.py, test/test_input_recipe.py, test/test_input_step.py, test/test_input_stringparser.py
Get rid of as many intermediate objects as possible during package calculation. This gives quite a speed bonus and dramatically lowers the memory consumption.
@kolewu @ThomasFeher This breaks the plugin API by removing some (hopefully) unused parameters. Old plugins should still work as long as they do not use these parameters. They are filled with stub values if the plugin announces an old API version. It would be good to get your feedbach if this is a deal-breaker for you.
=> Improve parsing speed and memory consumption

pym/bob/input.py
Without encoding=utf8 option recipes can only contain ascii characters. I think it should be possible to i.e. to add other characters to metaEnvironment and so on.
=> input: encode yaml with utf8

doc/manual/configuration.rst
From the headings it is not really visible that "build", "dev" and
"graph" belong to "command". Therefore the examples are changed to
contain "command", too. Also added one example for graph to make it
visible there, too.
=> doc: improve examples to make nesting more visible

pym/bob/cmds/build/build.py
instead of "forkserver", to start a new process.
Start method "forkserver" is only "available on Unix platforms, which
support passing file descriptors over Unix pipes" (see documentation of
"multiprocessing" module, section "Contexts and start methods"). This is
not the case for MSYS and leads to a "RuntimeError: received 0 items of
ancdata" in "/usr/lib/python3.7/multiprocessing/reduction.py", line 161,
in recvfds" for Python 3.7.
=> build: use start method "fork" on MSYS platforms

doc/manpages/bob-status.rst, pym/bob/scm/git.py
We propose to extend the behavior of `bob status` for Git repositories. We'd like to see not only unpushed commits on local branches but also from stash or the possibly detached HEAD for instance.
=> Extend "bob status" to check all unpushed commits of a Git repository

pym/bob/input.py, pym/bob/scm/url.py, test/url-scm-file/file.txt, test/url-scm-file/recipes/root.yaml, test/url-scm-file/run.sh
If the URL starts with '/', it is treated as a local file and is just copied
with 'cp' instead of downloaded using 'curl'.  This makes it possible to
easily build from tarballs in a sandbox that has no network access and no
'curl' command.
=> Allow local files with the "url" SCM.

doc/manpages/bob-status.rst, pym/bob/cmds/build/status.py, pym/bob/scm/scm.py
Handle the verbosity of detailed descriptions per flag. Each flag has a dedicated verbosity where modifying flags are shown by default.The detailed description of each flag is shown on the next severity level of that flag instead of all at once.
Fixes #231.
=> Streamline bob-status verbosity handling

pym/bob/scm/git.py, test/test_input_gitscm_status.py
Currently all tags that are not on a remote branch are flagged as unpushed commit. This is typically not true and almost always a false positive. Remove tags completely from the game because git does not know anyway which remote has what tags.
=> Fix status of unpushed tags

pym/bob/cmds/build/builder.py, pym/bob/cmds/jenkins.py, pym/bob/input.py
The execution path of a step depends on whether a sandbox is used or
not. That criteria has to be based on the state of the actually executed
step. In case the execution path of the dependencies of a step are computed
this decision must be based on the very same step.
The old logic looked only on the state of the step object and not the
one that is referring to it, tough. This is wrong if the dependency is
built in a sandbox and the dependent package is built outside. The
dependent package saw paths that were valid only in the sandbox.
Fixes #237.
=> input: compute exec path by referrer

doc/manpages/bob-project.rst, pym/bob/generators/QtCreatorGenerator.py
update of MR: https://github.com/BobBuildTool/bob/pull/235 
- I got no better solution that using pwd -W msys2 tool for getting the cwd/pwd in windows style.
- It is imported to start msys2 by "msys2_shell.cmd" to get WD environment-vaiable. I got no better solution to get install path of msys2 to execute bob by qt-creator.
- Replace "::" is important in some case, because of "C:/" shall not match and replaced to "C_/".
TODO
- finally there is one issue remaining: inside the qt-creator the project-explorer shows all directories starting at root point (e.g. "C:"), because of the source files not inside the directory of the project files. I have no idea how to solve this. (in linux it is solved by symlinks.)
=> ADD qtcreator support for windows by MSYS2

contrib/bash-completion, doc/manpages/bob-jenkins.rst, pym/bob/scm/git.py, test/test_jenkins_set_options.py
By default Jenkins has a timeout of 10 minutes for git clone and fetch
operations, sometimes this is not enough. With the setting the
"scm.git.timeout" it is possible to change the timeout.
=> input: git: add timeout option for Jenkins

pym/bob/scm/git.py
In pull request #236 checkout script for Git was extended to fetch tags explicitly (see c0034f8). Additionally also commits are now fetched explicitly.
But fetching commits explicitly may not be supported by git servers and can be denied, e.g. as follows:
```
error: Server does not allow request for unadvertised object
```
Since we have recipes, which reference specific commits, we suggest to change the behavior of the checkout script to not fetch commits explicitly.
Typically commits, which should be checked out are reachable by an existing branch and doesn't need to be fetched explicitly. Are there any use cases, where a commit should be checked out, which is not reachable by any branch, e.g. by a tag only which is not on a branch?
Otherwise the server configuration has to be changed, …
=> Don't fetch Git commits explicitly

pym/bob/archive.py, pym/bob/cmds/jenkins.py, test/test_archive.py, test/test_jenkins_set_options.py
Let's treat Windows and POSIX systems differently w.r.t. live build-ids. This should prevent artifact sharing problems when the same repository is used for Windows and Linux builds.
Contraty to #263 this is done automatically. It also fixes the unintended shell interpretation of URLs.
=> Fix artifact sharing

doc/manpages/bob-build-dev.rst, doc/manpages/bob-project.rst, pym/bob/cmds/build/build.py, pym/bob/cmds/build/builder.py, pym/bob/cmds/build/project.py
With download modules a regex can be used to specify which packages
should be downloaded.
Fixes #264
=> builder/project: add packages download option

setup.py
Since we have no proper way to interact with the user during install,
at least giving him or her an error message more human-readable than a
backtrace seems like a good idea.
There are two things that I've tried instead, to give a better onboarding experience - but that didn't work out:
* using `sphinx-pypi-upload` to pre-generate the man pages and push them individually to PyPI, but it seem - to put it mildly - unmaintained and it's in no way clear how it's _intended_ to work
* log an error message during install and then finish nevertheless, telling the user that if the man pages are actually needed, `pip install sphinx` followed by a `pip install --force-reinstall BobBuildTool` has to be run. This would also free the user from having to install `sphinx` in every `virtualenv`. Alas, …
=> Show an error message for missing sphinx

pym/bob/cmds/jenkins.py
Some jenkins plugins create @tmp directories in the workspace for some
reasons. Remove them as they influence the buildId calculation.
Fixes #273
=> jenkins: cleanup @tmp directories before build

pym/bob/cmds/jenkins.py
Special characters in the username and password are percent encoded in
URLs. When constructing the 'Authorization' HTTP header these fields
must first be converted to UTF-8 before calculating the digest.
Fixes #277.
=> jenkins: fix encoding of username/password

pym/bob/stringparser.py, test/test_input_stringparser.py
There is a bug in function `getSingleQuoted()` of class `StringParser`, which ignores a closing single quotation mark, if it is at the end of the string. This bug is fixed.
=> Fix detection of closing single quotation mark in StringParser

pym/bob/archive.py, pym/bob/cmds/build/builder.py, pym/bob/cmds/jenkins.py, pym/bob/fingerprints.py, pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py, pym/bob/generators/VisualStudio.py, pym/bob/input.py, pym/bob/scm/git.py, pym/bob/scm/scm.py, pym/bob/scm/svn.py, pym/bob/scm/url.py
Function `pipes.quote()` is deprecated since Python 2.7
see https://docs.python.org/2/library/pipes.html
=> Use function quote() from module shlex instead of pipes

pym/bob/generators/VisualStudio.py
Hi,
I added the local include paths of the module also to the include search paths for intellisense.
There was the problem, that !!SOME!! includes were not accessable by pressing F12 or STRG + left mouse button. (behavior was a bit strange, because some includes worked - but with this fix, all includes work fine).
BR.
=> generators: vs2019 add also local includes to include search paths

doc/manual/configuration.rst, doc/releases/0.16.rst, pym/bob/develop/version.py, pym/bob/input.py, pym/bob/utils.py, test/test_develop_version.py, test/test_utils.py
Convert git versions to PEP 440 versions. Change the version comparator to handle this format gracefully.
Fixes #290.
=> Consistently use PEP 440 version numbers

.travis.yml, setup.py
There is a small catch in handling the bdist_wheel upload. We have to
explicitly set the --plat-name. So we only let the sdist be built
automatically and build the bdist_wheel ourself before.
=> travis: upload tags automatically to PyPI

doc/manpages/bobpaths.rst, doc/manual/configuration.rst, pym/bob/input.py, pym/bob/scm/git.py, pym/bob/scm/scm.py, pym/bob/scm/svn.py, pym/bob/scm/url.py, pym/bob/stringparser.py, test/test_if_expression.py, test/test_input_recipe.py, test/test_input_recipeset.py
Support real expressions for the if property. This makes the if syntax
more readable.
E.g. instead of:
```
if: "$(or,$(eq,${FOO},bar),${BAZ})"
```
you can now write:
```
if: !expr |
"${FOO}" == "bar" || "${BAZ}"
```
=> input: add support for if-expressions

pym/bob/input.py
Some editors generate hidden temporary files while editing recipes
starting with a dot '.'. Ignore them during recipes / classes
collection. It's still allowed to use config or include files starting
with a dot.
Fixes #298
=> input: ignore hidden yaml files

doc/conf.py, doc/manpages/bob-query-path.rst, pym/bob/cmds/build/query.py, test/query-path/run.sh
This is a follow-up on #294 where we agreed on having both a `-q` and a `--fail` option for `bob query-path`.
=> Query path options

setup.py
The upcoming Jinja 3.0 version will require Python 3.6. Somehow the
Python3.5 pip will already fetch the alpha versions and fail badly.
Prevent that by requiring explicitly that Jinja2 must not be too new.
=> setup: retain Python3.5 compatibility

pym/bob/scm/cvs.py
The rework in 4e488a75 forgot to 'await' the commands, causing a warning to
be generated and the command being not executed:
cvs.py:74: RuntimeWarning: coroutine 'Invoker.checkCommand' was never awaited
----
In case this was a canary whether I'm still using it: of course I do! I even build MS-DOS programs with it now! :-)
=> cvs scm: make command invocation work again

.travis.yml, setup.py
Somehow the setuptools seem to download pre-release versions of
dependencies that are named in 'setup_requires'. This has been a hassle
before and now it fails again on some 'markupsafe' alpha version. Let's
try to install the sphinx dependency upfront with pip which should avoid
pre-release versions by default.
=> travis: fix CI build for Python 3.5

pym/bob/input.py, test/stable-variant-ids/specs/env.txt, test/stable-variant-ids/specs/include.txt, test/stable-variant-ids/specs/sandbox.txt, test/stable-variant-ids/specs/tools.txt
If a package has no buildScript then the results of the dependencies do
not contribute to the package content. It is still possible to build
deeper packages explicitly, though. Unfortunately the package graph
collapsed these empty packages during optimization even if the
sub-packages constituted different variants. This lead to incorrect
builds if multiple variants of dependencies from recipes without
a buildScript were defined.
Fixes #332.
=> input: prevent folding of empty packages in graph

pym/bob/utils.py, test/test_utils_dirhasher.py
We observed a Python exception in function `DirHasher.FileIndex.__writeEntry()` on a newly updated MSYS2 platform:
```
Bob version 0.16.0
Traceback (most recent call last):
File "/home/dachselt/bob/pym/bob/scripts.py", line 120, in catchErrors
ret = fun(*args, **kwargs)
File "/home/dachselt/bob/pym/bob/scripts.py", line 222, in cmd
cmd(args.args, bobRoot)
File "/home/dachselt/bob/pym/bob/scripts.py", line 27, in __develop
doDevelop(*args, **kwargs)
File "/home/dachselt/bob/pym/bob/cmds/build/build.py", line 288, in doDevelop
commonBuildDevelop(parser, argv, bobRoot, True)
File "/home/dachselt/bob/pym/bob/cmds/build/build.py", line 234, in commonBuildDevelop
builder.cook(backlog, True if args.build_mode == 'checkout-only' else False)
File "/home/dachselt/bob/pym/bob/cmds/build/builder.py", …
```
=> Fix format character for os.stat_result.st_ino in DirHasher.FileIndex.CACHE_ENTRY_FMT

pym/bob/archive.py, pym/bob/scm/url.py
Apparently, some hosts filter out the User-Agent set by urllib by
default, so we should include our own. For debugging purposes it's
probably a good idea to also include the current version, to identify
misbehaving changes.
The host this issue aroused with in this particular case is
https://swupdate.openvpn.org/, but of course this could happen
anywhere else, too.
=> scm/url: Include User-Agent

doc/manpages/bob-archive.rst, pym/bob/cmds/archive.py, test/archive/run.sh
This adds both a warning message when there haven't been any archive files found and a `--fail` option analogous to `bob query-path`.
I'm a bit unsure whether or not the `--fail` option should be a bit more aggressive, though, for example while detecting "wrong" files. I am happily awaiting feedback on this point.
Fixes #339
=> Small bob archive improvements

doc/manual/configuration.rst, pym/bob/input.py, test/tools-rename/config.yaml, test/tools-rename/output/result.txt, test/tools-rename/recipes/root.yaml, test/tools-rename/recipes/sub.yaml, test/tools-rename/recipes/tools.yaml, test/tools-rename/recipes/user.yaml, test/tools-rename/run.sh
Support remapping/replacing a tool by an existing one. This comes in handy when a dependency needs to be built by the host toolchain instead of the currently active cross toolchain.
Lays the ground to handle BobBuildTool/basement#11.
=> Tool remapping

pym/bob/generators/QtCreatorGenerator.py
with that, the path value will interpreted correctly again. #361
=> generator/qtcreator: escaping the path variable value

doc/manual/configuration.rst, pym/bob/cmds/build/build.py, pym/bob/cmds/build/builder.py, pym/bob/input.py, pym/bob/invoker.py, test/test_cmd_build_builder_jobserver.py
The make jobserver mechanism need two pipes. As long as it can read from
the request pipe new jobs are started. Once a job has finished a byte is
written back into the response pipe.
fixes: #257
=> builder: add simple make jobserver

doc/manpages/bob-status.rst, doc/manual/configuration.rst, pym/bob/scm/git.py, test/test_input_gitscm.py, test/test_input_gitscm_status.py
Instead of cloning all submodules it is possible to give a list of paths
to the "submodules" property. Only these submodules will be cloned and
all others will be left uninitialized. This is not possible for
sub-submodules.
@rhubert Is this sufficient for your use case?
=> Add support for cloning a subset of submodules

contrib/bash-completion/bob, doc/conf.py, doc/manpages/bob-show.rst, doc/manpages/index.rst, doc/manual/configuration.rst, pym/bob/cmds/show.py, pym/bob/input.py, pym/bob/scm/__init__.py, pym/bob/scm/scm.py, pym/bob/scripts.py, pym/bob/stringparser.py, pym/bob/tty.py, test/sandbox/recipes/root.yaml, test/sandbox/recipes/sandbox.yaml, test/sandbox/run.sh, test/show/config.yaml, test/show/recipes/dep.yaml, test/show/recipes/root.yaml, test/show/recipes/sandbox.yaml, test/show/recipes/tool.yaml, test/show/run.sh
The show command can be used to show all properties of a package as
they were computed by Bob when evaluating the recipes. The output can
be filtered and formatted in various ways. There is a special 'diff'
output format that produces a diff view of two packages.
=> Add "show" command

pym/bob/cmds/build/builder.py, pym/bob/invoker.py, pym/bob/scm/__init__.py, pym/bob/scm/git.py, pym/bob/scm/scm.py, pym/bob/scm/url.py, test/git-scm-switch/config.yaml, test/git-scm-switch/recipes/root.yaml, test/git-scm-switch/run.sh, test/git-scm-switch/submodules.yaml, test/run-tests.sh, test/test-lib.sh, test/url-scm-switch/config.yaml, test/url-scm-switch/correct-sha1-sha256.yaml, test/url-scm-switch/correct-sha1.yaml, test/url-scm-switch/file.txt, test/url-scm-switch/file2.txt, test/url-scm-switch/incorrect-sha1.yaml, test/url-scm-switch/recipes/root.yaml, test/url-scm-switch/run.sh
Add support for git and url SCMs to change certain properties without doing a clean checkout. The following changes are supported:
* git: changing commit/tag/branch and url
* url: changing the hash sums
If the inline upgrade fails the SCM will still moved to the attic and a clean checkout is done.
Fixes #346.
=> SCM inline switch support

pym/bob/cmds/build/builder.py, pym/bob/cmds/jenkins.py, pym/bob/input.py, test/test_input_recipeset.py
With the introduction of weak tools the build graph could get cycles
where the recipes and their package description are actually cycle free.
This can happen because the variant-id of a used weak tool is actually
not significant, causing distinct nodes to be collapsed into a single
one. The build logic will then get stuck because it assumes that the
graph is acyclic.
To work around this problem the optimizations enabled by weak tools are
partially reverted. Weak tools are only considered for the build-id
calculation and now let the variant-id untouched. This restores the
build behaviour that was present before weak tools were introduced. But
for binary artifacts weak tools are still considered. This keeps
compatibility with previously built artifacts and will still match
artifacts if the …
=> input: fix graph cycles on weak tools

contrib/bash-completion/bob, doc/manpages/bob-build-dev.rst, doc/manpages/bob-build.rst, doc/manpages/bob-dev.rst, doc/manual/configuration.rst, pym/bob/cmds/build/build.py, pym/bob/cmds/build/builder.py, pym/bob/input.py, test/layer-download/.gitignore, test/layer-download/classes/dummy.yaml, test/layer-download/config.yaml, test/layer-download/layers/componentA/recipes/A/A.yaml, test/layer-download/layers/componentA/recipes/A/A2.yaml, test/layer-download/layers/componentB/recipes/B/B.yaml, test/layer-download/recipes/C/C.yaml, test/layer-download/recipes/D/D.yaml, test/layer-download/recipes/root.yaml, test/layer-download/run.sh
With --download=forced-deps-layers dependencies are forced to be
downloaded if they are in a different layer than the package
given on the command line.
=> builder: add option to force download of deps in different layers

pym/bob/languages.py
The "-AsByteStream" parameter to "Set-Content" was introduced in pwsh
6.0. Before that "-Encoding Byte" could be used but this is not
supported on pwsh 6 anymore. Instead call the io.file.WriteAllBytes from
.NET which should be available everywhere.
Fixes #412.
=> languages: pwsh 5 compatibility

doc/manual/configuration.rst, pym/bob/generators/VisualStudio.py, pym/bob/generators/__init__.py, pym/bob/generators/common.py, pym/bob/input.py, pym/bob/utils.py
in MSYS2 with the update to python3.9 the platform string isn't "msys" anymore
the string is replaced by "cygwin".
we use isWindows or isMsys to check for the systems now.
.FIXES #416
=> python-3.9 + msys: platform string "msys" renamed by "cygwin"

pym/bob/cmds/build/builder.py
The asyncio.CancelledError class was the same as
concurrent.futures.CancelledError in the past. Recently it was converted
to its own class, leading to visible backtraces.
=> builder: catch the correct CancelledError

doc/manpages/bob-ls.rst, pym/bob/cmds/misc.py
By default only unique packages are displayed. The -A option shows all
identical packages too, instead of only the first one.
Fixes #338.
=> ls: add option to show identical packages too

pym/bob/generators/VisualStudio.py
In commit 192d78f4 the project template was incorrectly adapted and now
had a backslash as file start. Similarly, the header of the solution
files had an empty line at the beginning.
Fixes #448.
=> VisualStudio: fix generated files

doc/manpages/bob-project.rst, pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py, pym/bob/generators/common.py
Additional include directories are added last to the IDE search paths.
These directories were previously scanned recursively but the code to do
that was broken. Instead forward the paths literally to the IDE. If
multiple sub-directories need to be added the user can always give
another "-I" option.
Fixes #451.
=> generators: do not scan additional include dirs recursively

doc/manual/configuration.rst, pym/bob/input.py, test/test_input_recipe.py, test/test_input_recipeset.py
Normally dependencies are only available to the buildScript. But
sometimes it is necessary to access dependencies in the checkoutScript
already. Currently this requires to copy the sources in the
buildScript where access to all dependencies is possible.
The newly added checkoutDeps keyword takes a list of dependencies that
shall be available to the checkoutScript. The names must be given
exactly and they must be a valid dependency. Provided dependencies of
such named packages are *not* implicitly made available. The number of
checkout dependencies should be kept as small as possible to prevent
accidental creation of checkout variants which are usually confusing to
users.
=> input: add checkoutDep dependency flag

pym/bob/input.py
The CoreRef.refDeref() method needs to reconstruct the concrete
Step/Package from the reduced core graph. There is a cache to prevent
unneeded dereferencing of already seen edges. Unfortunately the cache
was not filled for sandbox references. Depending on the complexity of
the sandbox partial graph this could drastically increase the time to
traverse the graph.
=> input: cache sandbox when reconstructing graph

pym/bob/cmds/build/builder.py
It is not necessary to update the buildDigest in case `--checkout-only`
is set, obviously. This can avoid rebuilds in case an update of the
sources was done using `--checkout-only` without `--sandbox` and then
rebuilding with `--sandbox` for example.
=> builder: check earlier for checkout-only flag

pym/bob/utils.py
On Windows the stat.st_ino field is a 64-bit unsigned integer. The
DirHasher got this already correct but binStat() was using signed 64
bit which might overflow. POSIX also defines ino_t as unsigned integer type.
Fixes #464.
=> utils: fix crash on large stat.st_ino fields

pym/bob/scm/git.py, test/test_input_gitscm.py
Fixes the following error:
File "../pym/bob/scm/git.py", line 226, in invoke
await self.__checkoutTag(invoker, fetchCmd, switch)
File "../pym/bob/scm/git.py", line 253, in __checkoutTag
self.fail("Plain git-fetch in", self.__dir,
AttributeError: 'GitScm' object has no attribute 'fail'
raised if shallow clone is active and the commit can't be reached.
Also add some coverage for the failing line.
=> git: fix AttributeError in error message

pym/bob/input.py
There are mismatching names in whitelist.
MSYS2 is handling the names case-sensitive, but not native windows.
.FIXES #473
=> input: fixed typos for MSYS2 environment variables in whitelist

pym/bob/generators/common.py, pym/bob/input.py, pym/bob/scm/url.py, pym/bob/state.py, pym/bob/utils.py, test/test_utils.py
Replacing a file on Windows might fail spuriously. Add some mitigation that hopefully masks this transient errors...
=> Fix spurious file renaming errors on Windows

pym/bob/scm/git.py
Use the replacement error handling to avoid UnicodeDecodeErrors like
this:
```
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.20.1.dev12+g71b3cba
Traceback (most recent call last):
File "bob/pym/bob/scripts.py", line 153, in catchErrors
ret = fun(*args, **kwargs)
File "bob/pym/bob/scripts.py", line 254, in cmd
ret = cmd(args.args, bobRoot)
File "bob/pym/bob/scripts.py", line 74, in __status
doStatus(*args, **kwars)
File "bob/pym/bob/cmds/build/status.py", line 300, in doStatus
printer.showAllDirs(args.attic)
File "bob/pym/bob/cmds/build/status.py", line 218, in showAllDirs
status = getScm(scmSpec).status(workspace)
File "bob/pym/bob/scm/git.py", line 689, in status …
```
=> git: handle encoding errors

pym/bob/develop/version.py, pym/bob/invoker.py, pym/bob/scm/cvs.py, pym/bob/scm/git.py, pym/bob/scm/svn.py, pym/bob/utils.py
It's always possible for a sub-process to return strings with an invalid
encoding. Make sure this does not lead to a crash. The 'surrogateescape'
handler is not correct because it would also be required on all encoding
paths which is not easily possible.
=> Consistently use 'replace' unicode error handler

doc/manual/configuration.rst, pym/bob/stringparser.py, test/unit/test_if_expression.py, test/unit/test_input_stringparser.py
Query defined variables of a tool. The tool must only be defined and is
not required to be used by the recipe.
Fixes #486.
=> stringparser: add get-tool-env function

.github/workflows/workflow.yaml
In contrast to Linux the default Java version on Windows is still 1.8. Explicitly use Java 11 to satisfy the Jenkins prerequisites.
=> workflow: use Java 11 on Windows

doc/manpages/bob-build-dev.rst, doc/manual/configuration.rst, pym/bob/builder.py, pym/bob/cmds/invoke.py, pym/bob/input.py, pym/bob/intermediate.py, pym/bob/invoker.py, pym/bob/languages.py, pym/bob/stringparser.py, test/black-box/checkout-update/classes/no-update.yaml, test/black-box/checkout-update/classes/update.yaml, test/black-box/checkout-update/config.yaml, test/black-box/checkout-update/recipes/deterministic-root.yaml, test/black-box/checkout-update/recipes/indeterministic-root.yaml, test/black-box/checkout-update/run.sh, test/black-box/fingerprints/recipes/conditional.yaml, test/test-lib.sh, test/unit/test_input_recipe.py
By default no checkout scripts are run when building with `--build-only`.
Some use cases practically require the `checkoutScript` to be always run,
through. A typical example are code generators that generate sources
from some high level description. These generators must be run every
time when the user has changed the input. A recipe or class can
explicitly opt in to run their `checkoutScript` also in build-only mode to
cover such a use case. This is done by either setting `checkoutUpdateIf`
to `True` or by a boolean expression that is evaluated to `True`. Otherwise
the `checkoutScript` is ignored even if some other class enables its
script. The `checkoutUpdateIf` property thus only applies to the
corresponding `checkoutScript` in the same recipe/class.
=> Run selected checkoutScripts in build-only mode

.github/workflows/workflow.yaml
The GitHub action PyPI upload does not work on Windows. Instead gather all binary wheels and the source distribution and publish at once in a separate job.
=> workflow: fix upload to PyPI from Windows

pym/bob/generators/common.py
If a package has a host executable file but has no checkout step, the common scanner would fail:
...
File "C:\Projects\tools\bob\pym\bob\generators\common.py", line 246, in collect
collect(d.getPackage(), False)
File "C:\Projects\tools\bob\pym\bob\generators\common.py", line 224, in collect
info.scan._addRunTarget(target)
AttributeError: 'NoneType' object has no attribute '_addRunTarget'
Use a correct sentinel to mock the expected interface.
Fixes #498.
=> generators: fix crash on packages without checkout

pym/bob/input.py
attic was missing in this schema, so it was not possible to use it in user configurations
=> add missing schema option attic

doc/manual/configuration.rst, pym/bob/input.py, pym/bob/tty.py
Make the threshold customizable as some people were confused about the new MassiveParallelTUI. They wished to get the old TUI back without being limited to 16 jobs.
=> tty: make the MassiveParallelTUI threshold settable

pym/bob/generators/EclipseCdtGenerator.py, pym/bob/generators/QtCreatorGenerator.py
If a invalid regular expression is provided a parse error should be shown. Unfortunately the error reporting was broken and raised another exception:
raise ParseError("Invalid regular expression '{}': {}".format(e.pattern), e)
NameError: name 'ParseError' is not defined
raise ParseError("Invalid regular expression '{}': {}".format(e.pattern), e)
IndexError: Replacement index 1 out of range for positional args tuple
=> generators: fix ParseError reporting

pym/bob/archive.py
The azure-storage-blob python library interfaces has changed substantially. Adapt accordingly.
Fixes #505.
=> archive: fix azure backend

doc/manual/extending.rst, pym/bob/cmds/build/project.py, pym/bob/generators/__init__.py, pym/bob/input.py, test/black-box/generator/config.yaml, test/black-box/generator/output-plugin-g2.txt, test/black-box/generator/plugins/g2.py, test/black-box/generator/recipes/root.yaml, test/black-box/generator/run.sh
While many of the generators do not need it there are use cases where a generator needs to handle a pathspec rather than a package-path.
=> project-generators: enable use of query language

pym/bob/scm/git.py
It's still possible to do inline switching if the useCommitOnBranch property changes.
=> git: filter useCommitOnBranch in canSwitch

doc/manual/policies.rst, pym/bob/builder.py, pym/bob/cmds/build/clean.py, pym/bob/cmds/build/status.py, pym/bob/input.py, pym/bob/intermediate.py, pym/bob/scm/__init__.py, pym/bob/scm/imp.py, pym/bob/state.py, test/black-box/checkout-update/recipes/deterministic-root.yaml, test/black-box/checkout-update/run.sh, test/black-box/import-scm/config.yaml, test/black-box/import-scm/root.yaml, test/black-box/import-scm/run.sh
If a recipe utilizes `checkoutUpdateIf`, relax the checks so that also modified `checkoutScript`s are run in build-only mode.
@rhubert  Could you please give it a try?
:warning: This change bumps the project state version. Once used in a build tree, there is no going back to an older Bob version! So maybe better test it in a new build tree.
=> Run changed checkoutScript in build-only mode

pym/bob/scm/git.py, test/unit/test_input_gitscm_status.py
@aaronpohle Could you test this MR and see if it fixes your problem?
=> Handle nested git tags

pym/bob/scm/url.py
Turns out that at least tarfile is not usable on POSIX systems for us due to the `chmod` handling. Play safe and use it only on native Windows where this doesn't make a difference. Given that, we can also prefer the Python versions there.
=> Use internal extractors on win32

pym/bob/generators/common.py
Fix for exceptions occurring when using the filter option:
```
File "pym/bob/generators/common.py", line 309, in configure
additionalFiles = re.compile(args.filter) if self.args.filter else None
NameError: name 'args' is not defined
File "pym/bob/generators/common.py", line 311, in configure
raise ParseError("Invalid regular expression '{}': {}".format(e.pattern), e)
NameError: name 'ParseError' is not defined
File "pym/bob/generators/common.py", line 311, in configure
raise ParseError("Invalid regular expression '{}': {}".format(e.pattern), e)
IndexError: tuple index out of range
```
=> generators: fix filter option and error reporting

pym/bob/languages.py
there is no CYGWIN_VERSION_DLL_EPOCH anymore. epoch and major has to be calculated. define CYGWIN_VERSION_DLL_MAJOR 3004 means version 3.4.x.
=> msys: fixed version handling

pym/bob/scm/git.py, test/black-box/git-scm-switch/run.sh
If gitCommitOnBranch is active and commit and branch are configured in the recipe changing the commit back to a older one did not update the sources back to the configured version. Instead the remained on the current version.
=> git: fix scm switch when going back to older revision

pym/bob/scm/git.py
There is no need to move the workspace to attic if the reference or dissociate are changed.
=> git: inline switch when reference changes

test/integration/jenkins/run.py
Looks like Windows sometimes needs more time.
=> test: increase timeouts for Jenkins integration test

pym/bob/scm/url.py
Fix a crash on a system without 'unzip':
```
Traceback (most recent call last):
File "/bob/pym/bob/scripts.py", line 146, in catchErrors
ret = fun(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "/bob/pym/bob/scripts.py", line 254, in cmd
ret = cmd(args.args, bobRoot)
^^^^^^^^^^^^^^^^^^^^^^^
File "/bob/pym/bob/scripts.py", line 29, in __develop
doDevelop(*args, **kwargs)
File "/bob/pym/bob/cmds/build/build.py", line 410, in doDevelop
commonBuildDevelop(parser, argv, bobRoot, True)
File "/bob/pym/bob/cmds/build/build.py", line 345, in commonBuildDevelop
builder.cook([ExecutableStep.fromStep(b, LazyIR) for b in backlog],
File "/bob/pym/bob/builder.py", line 916, in cook
raise self.__buildErrors[0]
File "/bob/pym/bob/builder.py", line 811, in __taskWrapper
ret = await coro()
^^^^^^^^^^^^
File …
```
=> scm/url: fix crash if no extractor is installed

doc/manual/configuration.rst, pym/bob/input.py, pym/bob/intermediate.py, pym/bob/scm/__init__.py, pym/bob/scm/url.py, test/unit/mocks/http_server.py, test/unit/test_input_urlscm.py
=> Add mirrors support for URL SCMs

pym/bob/builder.py, pym/bob/tty.py
Don't delay the execution of audits to finish jobs as soon as possible when the build/package script has returned. Also include the audit into a visible action so that the user knows the build/package step has not finished yet.
Fixes #539
=> Fix audit execution

src/namespace-sandbox/namespace-sandbox.c
The pull request relates to https://github.com/BobBuildTool/bob/issues/554
=> Fix sandbox pseudoterminals

pym/bob/scm/git.py
Some minor bug fixes when switching between git branches...
=> Fix git branch switch

doc/manual/configuration.rst, pym/bob/input.py, pym/bob/intermediate.py, pym/bob/invoker.py, pym/bob/languages.py, src/namespace-sandbox/namespace-sandbox.c, test/black-box/sandbox/as-root.yaml, test/black-box/sandbox/as-self.yaml, test/black-box/sandbox/recipes/root.yaml, test/black-box/sandbox/run.sh
This patch is used to address the issue of needing to use a specific user ID during the compilation phase to connect to the server and validate the compiler license legality, e.g. QNX project qcc compiler need to check license via online server
=> Let sandbox supports custom user information settings

doc/manual/configuration.rst, pym/bob/input.py, test/unit/test_input_recipeset.py
This property controls the inheritance of environment, tools and sandbox
for a dependency. It defaults to true so everything is inherited.
If set to `false` environment, tools and sandbox are dropped. The
dependency starts with the default-environment, no tools and no sandbox.
This becomes particularly useful when an existing root-package should
become a dependency of another root-package, e.g. for building an
installer.
=> input: add 'inherit' dependency property

pym/bob/builder.py
The builds step implicitly depends on the execution path of all dependencies, even for tools.
=> builder: consider all execution paths

doc/manual/configuration.rst, pym/bob/input.py, test/black-box/checkoutAssert/recipes/root.yaml, test/black-box/checkoutAssert/run.sh
If variables are used to control the checkout of a package the checkoutAssert might need to be variable as well.
=> input: apply env substition to checkoutAssert

pym/bob/scm/git.py
The user can enable the recursive submodule handling in the global git config. Bob does the update of submodules manually but apparently we missed some git call sites.
Fixes #568.
=> git: do not recurse automatically into submodules

pym/bob/cmds/show.py, test/black-box/show/recipes/dep.yaml
Fix a regression of 0c40313b:
File "pym/bob/cmds/show.py", line 54, in <listcomp>
{ k:v for k,v in a.getProperties().items() if not k.startswith("__") }
^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'getProperties'
and add a test for this.
=> show: fix crash with checkoutAssert

pym/bob/archive.py, pym/bob/scm/url.py, test/unit/test_archive.py
Do not assume that parent directories are created implicitly.
=> Better binary artifacts WebDAV compliance

doc/manual/configuration.rst, pym/bob/input.py, test/unit/test_input_recipe.py
=> input: apply env substitution to metaEnvironment

.github/workflows/workflow.yaml
This won't resolve the failed coverage uploads on pull requests, though. But main repository builds should become stable and always update the coverage.
=> github: use upload token for coverage

pym/bob/scripts.py
If the user gives a color mode on the command line, apply the mode immediately. Otherwise the mode was not applied until some recipes layer was successfully parsed. Because error messages are already colored, that created some inconsistent behaviour.
Fixes #578.
=> scripts: set cmd line color mode immediately

doc/manual/configuration.rst, pym/bob/cmds/show.py, pym/bob/input.py, pym/bob/intermediate.py, test/unit/test_input_recipeset.py, test/unit/test_input_step.py
Add support for conditional tool usage...
=> Conditional tools

pym/bob/stringparser.py, test/unit/test_input_stringparser.py
Fix constructs like `${VAR:+${VAR}}` that fail so far.
=> Fix variable substitutions with unused parts

pym/bob/scm/git.py, test/black-box/git-scm-switch/run.sh
If a git-workspace is in a detached HEAD state and the recipe has been updated to point to the same commit there is no need to move this into attic.
=> git: do not move detached HEAD to attic if same commit

contrib/bash-completion/bob, doc/conf.py, doc/manpages/bob-layers.rst, doc/manpages/index.rst, doc/manual/configuration.rst, pym/bob/builder.py, pym/bob/cmds/build/build.py, pym/bob/cmds/layers.py, pym/bob/input.py, pym/bob/layers.py, pym/bob/scripts.py, pym/bob/state.py, test/black-box/commands/run.sh, test/black-box/layers-checkout/__layers/bar/2/recipes/bar.yaml, test/black-box/layers-checkout/__layers/baz/1/recipes/baz.yaml, test/black-box/layers-checkout/__layers/baz/2/recipes/baz.yaml, test/black-box/layers-checkout/__layers/foo/config.yaml, test/black-box/layers-checkout/__layers/foo/recipes/foo.yaml, test/black-box/layers-checkout/config.yaml, test/black-box/layers-checkout/layers_overrides.yaml, test/black-box/layers-checkout/recipes/root.yaml, test/black-box/layers-checkout/run.sh, test/unit/test_input_recipe.py, test/unit/test_input_recipeset.py
This is a very rough first draft of support for layers handled by bob to get some early comments about this.
The idea is to add a scm-spec to the `layers` section of the `config.yaml`:
```yaml
layers:
- foo:
scm: git
url: git@foo:/foo.git
branch: master
commit: ....
```
A layer specified like this also changes the behavior when using nested layers where multiple layers depend on the same layer as the layer structure is flattened and each layer is checked out only once. This make it possible to have the same recipes either used as root-recipes repo or as layer from another recipes package. (ATM this is done by matching the name of the layer only, maybe the url should be used instead or a additional `uuid`,... ??)
ATM a internal `.bob_layers` root package is generated for this with …
=> bob managed layers

pym/bob/layers.py
If a layer was checked out by bob and deleted by the user it was never recreated.
=> layers: fix checkout of deleted layer

contrib/bash-completion/bob, doc/manpages/bob-layers.rst, doc/manual/configuration.rst, pym/bob/cmds/build/build.py, pym/bob/cmds/layers.py, pym/bob/input.py, pym/bob/layers.py, pym/bob/utils.py, test/black-box/layers-checkout/__layers/bar/2/recipes/bar.yaml, test/black-box/layers-checkout/__layers/baz/1/recipes/baz.yaml, test/black-box/layers-checkout/__layers/baz/2/recipes/baz.yaml, test/black-box/layers-checkout/__layers/foo/config.yaml, test/black-box/layers-checkout/__layers/foo/recipes/foo.yaml, test/black-box/layers-checkout/run.sh
This fixes a couple of subtle corner cases that so far got unnoticed:
* We still parsed the system- and user-global default.yaml
configuration files. The data from these files was not used except
the URM SCM mirrors. Now everything depends just on the layer
configuration files.
* The layersScmOverrides and layersWhitelist keys were only
appended when traversing the layers. This causes settings of
unrelated layers to affect each other. Now the layer settings are
handled strictly hierarchical.
* It was possible to switch to the "import" SCM via layersScmOverrides.
This is prevented now by always using the layers SCM schema.
* There were no default environment white list entries. This was
inconsistent to the regular white list handling.
Additionally, it improves the following things:
* Use …
=> Fix some layers inconsistencies

doc/manual/configuration.rst, doc/manual/policies.rst, pym/bob/input.py, test/unit/test_input_recipe.py
Using bob 0.25 on older recipes with unfortunate metaEnvironment strings raises a parse error. Add a policy to issue a warning only.
=> input: add substituteMetaEnv policy

.github/workflows/workflow.yaml
The setup-java action should be sufficient.
=> workflow: fix java selection on Windows

doc/manual/configuration.rst, doc/manual/policies.rst, pym/bob/builder.py, pym/bob/cmds/build/build.py, pym/bob/input.py, pym/bob/layers.py, test/black-box/layers-checkout/config.yaml, test/black-box/layers-checkout/run.sh, test/unit/test_input_recipeset.py
Add the managedLayers policy for backwards compatibility.
Fixes #595.
=> Restore pre-0.25 nested layers compatibility

pym/bob/audit.py, pym/bob/cmds/graph.py, pym/bob/cmds/jenkins/exec.py, pym/bob/cmds/jenkins/intermediate.py, pym/bob/cmds/jenkins/jenkins.py, pym/bob/input.py, pym/bob/layers.py, pym/bob/scm/__init__.py, pym/bob/scm/cvs.py, pym/bob/scm/git.py, pym/bob/scm/svn.py, pym/bob/scm/url.py
Plus a couple of other fixes...
=> Add managed layers to audit trail

doc/manpages/bobpaths.rst
There is a double `not` in `Alias substitution` section
=> Fix typo in bobpaths.rst

pym/bob/scm/git.py, src/namespace-sandbox/namespace-sandbox.c, test/black-box/buildid-change/run.sh, test/black-box/clean/run.sh, test/black-box/fingerprints/recipes/sandbox.yaml, test/black-box/git-alternatives/run.sh, test/black-box/git-scm-retry/run.sh, test/black-box/git-scm-switch/run.sh, test/black-box/git-scm/run.sh, test/black-box/nested-scms/run.sh, test/black-box/status/run.sh, test/integration/jenkins/run.py, test/unit/test_input_gitscm.py, test/unit/test_input_gitscm_status.py
A series of small fixes and adjustments to get the unit tests working on arch linux based distributions using the latest versions of git, different `hostname`, latest java, ...
=> fix unit tests on arch linux

doc/manual/configuration.rst
Bob return failure when use `disassociate` in `checkoutSCM` section 
```
Parse error: Error while validating recipes/bob.yaml: Key 'checkoutSCM' error:
Wrong key 'disassociate' in {'scm': 'git', 'url': 'git@github.com:BobBuildTool/bob.git', 'branch': 'master', 'singleBranch': True, 'shallow': 1, 'disassociate': True}
```
Browse through the source code and `dissociate` is defined and used instead. 
Also fix typo and add man page section that explains the option
=> doc: Fix incorrect option "disassociate" in "checkoutSCM" git section

test/unit/test_input_gitscm.py
Looks like the default remote branch is sometimes displayed by git. Remove it to not be confused when comparing with expected branch set.
=> test: filter HEAD from remote branch list

doc/manual/configuration.rst, pym/bob/builder.py, pym/bob/cmds/jenkins/jenkins.py, pym/bob/input.py, test/unit/test_input_recipeset.py
Virtual packages transparently create an alias for a recipe. They are configured by yaml files in the newly defined `virtual` directory. For example, the file `virtual/libs/libegl.yaml`
```
multiPackage:
"":  ${CONFIG_SELECT_LIBEGL:-libs::mesa3d}
dev: ${CONFIG_SELECT_LIBEGL:-libs::mesa3d}-dev
tgt: ${CONFIG_SELECT_LIBEGL:-libs::mesa3d}-tgt
```
would create packages `libs::libegl`, `libs::libegl-dev` and `libs::libegl-tgt` whose underlying recipe is selected by `CONFIG_SELECT_LIBEGL`.
If there is only one package, the yaml file can be a simple string containing just the target name.
=> input: add support for package aliases

src/namespace-sandbox/namespace-sandbox.c
Some tools use this while building. E.g. the python multiprocessing library uses this for its locking mechanism.
=> sandbox: mount dev/shm

pym/bob/scm/url.py, test/black-box/extractors/run.sh
With the introduction of separate download directories in 2dffbccc, the extraction canary had changed its name. This change affects the source hash in case the urlScmSeparateDownload is kept on the old behaviour, though. To keep backwards compatibility, name the canary exactly like before.
=> url: fix canary name of extracted archives

pym/bob/scm/url.py
Before accessing any members of the old SCM, we need to make sure that it has the same type. Thus, the test for the "scm" property in the diff has to come first.
=> url: fix crash when switching between git and url SCM

pym/bob/cmds/archive.py
A return in the finally block silently swallows the exception instead of reraising it. This caused archive scanning to be silently stopped on a exception and results in many unhandled archives.
=> cmds/archive: fix lost exception

contrib/plugins/path-fmt.py, doc/manual/extending.rst, pym/bob/input.py, test/black-box/plugin-states/plugins/path-fmt.py, test/black-box/plugin-states/recipes/lib1.yaml, test/black-box/plugin-states/recipes/root.yaml
Just like for custom settings in default.yaml, plugin defined recipe properties and state trackers shall not start with a lower case letter. This namespace is reserved by Bob for future extensions.
=> input: custom properties must not start with lower case

test/unit/mocks/http_server.py, test/unit/test_archive.py
Internally, send_error() already calls end_headers(). Doing it twice will race with the client and provokes a BrokenPipeError if the client closed its connection faster than we could send the blank line.
=> test: do not call end_headers() after send_error()

doc/manpages/bob-archive.rst, doc/manual/configuration.rst, pym/bob/archive.py, pym/bob/cmds/archive.py, pym/bob/input.py, pym/bob/webdav.py, test/black-box/archive-mirror/run.sh, test/black-box/archive/run.sh, test/black-box/audit/run.sh, test/black-box/buildid-change/run.sh, test/black-box/fingerprintVars/default.yaml, test/black-box/fingerprints/default.yaml, test/black-box/layer-download/run.sh, test/black-box/non-relocatable/run.sh, test/black-box/parallel/default.yaml, test/black-box/sandbox-fingerprints/run.sh, test/black-box/shared-pkg/run.sh, test/unit/mocks/http_server.py, test/unit/mocks/jenkins_tests.py, test/unit/test_archive.py, test/unit/test_input_recipeset.py, test/unit/test_webdav.py
relates to issue https://github.com/BobBuildTool/bob/issues/340
=> Make bob archive work remotely

pym/bob/webdav.py, test/unit/test_webdav.py
deleting a file that is not there (anymore) should not throw an exception. this caused some issues in our company's interal CỊ where cache issues lead to delete attempts on files that were already gone
=> webdav: do not consider 404 an error for delete

doc/manual/configuration.rst, pym/bob/input.py, test/unit/test_input_recipeset.py
Some tools require other tools to work. Add a "dependTools" and "dependToolsWeak" property to the tools definition. Everything that is listed there will be added to the used (weak) tools of a package.
=> input: tool dependencies

doc/manual/configuration.rst, pym/bob/cmds/show.py, pym/bob/input.py, test/unit/test_input_recipe.py
Allow a boolean string or an IfCondition as value of the "shared"
attribute. Sometimes a package could be used for host and target builds.
Only in case of the former it makes sense to share the artifact.
=> Conditional share attribute

doc/manual/configuration.rst, pym/bob/input.py, test/unit/test_input_recipeset.py
=> Package step dependencies

doc/manual/configuration.rst, pym/bob/input.py, pym/bob/scm/url.py
Some servers need additional informations provided by custom headers.
Add a `headers` attribute where the user can set these custom headers.
=> Urlscm: add support for custom headers
